# Auto-generated by hack/write-package-list.sh — do not edit manually
# Annotate files in assets/ with '# pkg:brew=name', '# pkg:cask=name', etc.

brew "argocd"
brew "bat"
brew "fzf"
brew "gh"
brew "helm"
brew "kubernetes-cli"
brew "mise"
brew "starship"
brew "zsh-autosuggestions"
cask "ghostty"
