#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

BREWFILE="$PROJECT_ROOT/Brewfile"
MISE_CONFIG="$PROJECT_ROOT/assets/.config/mise/config.toml"
CURL_TXT="$PROJECT_ROOT/curl-installs.txt"

TEMP_BREW=$(mktemp)
TEMP_CASK=$(mktemp)
TEMP_TAP=$(mktemp)
TEMP_MAS=$(mktemp)
TEMP_MISE=$(mktemp)
TEMP_CURL=$(mktemp)
trap "rm -f $TEMP_BREW $TEMP_CASK $TEMP_TAP $TEMP_MAS $TEMP_MISE $TEMP_CURL" EXIT

ASSETS_DIR="$PROJECT_ROOT/assets"

extract_manager() {
    local manager="$1"
    local outfile="$2"
    grep -rh "# pkg:${manager}=" "$ASSETS_DIR" 2>/dev/null | \
    while IFS= read -r line; do
        value="${line##*# pkg:${manager}=}"
        IFS=',' read -ra items <<< "$value"
        for item in "${items[@]}"; do
            item=$(printf '%s' "$item" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            [ -n "$item" ] && echo "$item"
        done
    done | sort -u >> "$outfile" || true
}

extract_manager "brew" "$TEMP_BREW"
extract_manager "cask" "$TEMP_CASK"
extract_manager "tap"  "$TEMP_TAP"
extract_manager "mas"  "$TEMP_MAS"
extract_manager "mise" "$TEMP_MISE"
extract_manager "curl" "$TEMP_CURL"

total=$(cat "$TEMP_BREW" "$TEMP_CASK" "$TEMP_TAP" "$TEMP_MAS" "$TEMP_MISE" "$TEMP_CURL" | grep -c . 2>/dev/null || echo 0)
if [ "$total" -eq 0 ]; then
    echo "⚠ No packages found — aborting to prevent overwriting existing files" >&2
    exit 1
fi

# Generate Brewfile
{
    echo "# Auto-generated by hack/write-package-list.sh — do not edit manually"
    echo "# Annotate files in assets/ with '# pkg:brew=name', '# pkg:cask=name', etc."
    echo ""
    [ -s "$TEMP_TAP" ]  && while IFS= read -r v; do printf 'tap "%s"\n' "$v"; done < "$TEMP_TAP"
    [ -s "$TEMP_BREW" ] && while IFS= read -r v; do printf 'brew "%s"\n' "$v"; done < "$TEMP_BREW"
    [ -s "$TEMP_CASK" ] && while IFS= read -r v; do printf 'cask "%s"\n' "$v"; done < "$TEMP_CASK"
    [ -s "$TEMP_MAS" ]  && while IFS= read -r v; do
        if [[ "$v" == *:* ]]; then
            name="${v%%:*}"; id="${v#*:}"
            printf 'mas "%s", id: %s\n' "$name" "$id"
        else
            printf 'mas "%s", id: %s\n' "$v" "$v"
        fi
    done < "$TEMP_MAS"
} > "$BREWFILE"
echo "✓ Brewfile: $(grep -c '^\(brew\|cask\|tap\|mas\)' "$BREWFILE" || true) entries"

# Generate assets/.config/mise/config.toml
mkdir -p "$(dirname "$MISE_CONFIG")"
{
    echo "# Auto-generated by hack/write-package-list.sh — do not edit manually"
    echo ""
    echo "[tools]"
    awk '
    {
        if (match($0, /@/)) { tool=substr($0,1,RSTART-1); ver=substr($0,RSTART+1) }
        else                  { tool=$0; ver="latest" }
        if (tool in t) { t[tool]=t[tool] ",\"" ver "\"" }
        else           { t[tool]="\"" ver "\""; order[++n]=tool }
    }
    END {
        for (i=1;i<=n;i++) {
            tool=order[i]; v=t[tool]
            if (index(v,",")>0) printf "%s = [%s]\n", tool, v
            else                printf "%s = %s\n",   tool, v
        }
    }' "$TEMP_MISE"
} > "$MISE_CONFIG"
tool_count=$(grep -v '^\[' "$MISE_CONFIG" | grep -c '=' 2>/dev/null || echo 0)
echo "✓ assets/.config/mise/config.toml: $tool_count tools"

# Generate curl-installs.txt
cp "$TEMP_CURL" "$CURL_TXT"
echo "✓ curl-installs.txt: $(wc -l < "$CURL_TXT" | tr -d ' ') entries"
